### ISSUE TITLE
server side pdf creation

### ISSUE THREAD

**Issue by suryaiiit** [NilsDannemann/meteor-pdfmake#2]
How to create the pdf on server side?

Thanks.

**Comment by NilsDannemann** [comment]
I'm not sure, since the docs aren't clear on that. 
At this point I think this package is best used for the client-side solution.

For server side you might take a look at this solution from the meteor forums:
https://forums.meteor.com/t/send-pdf-from-server-to-client/6246/13

Hope that works for you.
